### ISSUE TITLE
Implement bloom filter

### ISSUE THREAD

**Issue by oed** [ceramicnetwork/ceramic-anchor-service#98] opened 2020-09-16 09:17 UTC

**Comment by stbrody** [comment] 2020-12-03 19:42
I want to clarify something about the bloom filter contents: currently the CAS only has access to individual records, not entire documents, so the bloom filter will include the data (family, tags, etc) only if they show up in the specific record getting anchored.  That means the bloom filter stores whether any changes to those fields happened, not whether any changes to documents with those fields happened.  That also means the bloom filter will only contain the new value, not the old value for each metadata field.  Does that all make sense @oed?

**Comment by stbrody** [comment] 2020-12-03 19:45
Hmm... this is also going to be weird because the records only contain the JSONPatch diff to the contents/metadata.  I'm not sure how easy it is to parse the diff to find the fields that are changing and the values they are changing to...

**Comment by stbrody** [comment] 2020-12-03 19:48
This doesn't really seem like it was the intent behind CIP-69.  I feel like CIP-69 was expecting that the bloom filter contains metadata about the *documents* that changed, regardless of how they changed.  Is it time to actually embed a full js-ceramic node into the CAS so that we can have access to the full document state?  If so, that's probably a bigger change and refactoring to do well...

**Comment by stbrody** [comment] 2020-12-03 19:48
FYI @simonovic86

**Comment by stbrody** [comment] 2020-12-03 20:10
Okay, it looks like we do in fact already have access to a Ceramic API within the CAS for resolving 3ids: https://github.com/ceramicnetwork/ceramic-anchor-service/blob/e59455578ce51d9f0b684b6c5058fe9b1db26e26/src/services/ceramic-service.ts#L32.

So we can use that to fetch the state of the document, but we'll need to expose a way to load the document at a version corresponding to a specific signed record, where currently only anchor records are exposed as query-able versions.  Does this seem like the right way forward @oed?  I want to make sure I've interpreted your original intent correctly.

**Comment by oed** [comment] 2020-12-04 08:51
I think the idea was to use our gateway instance ( see url here: https://github.com/3box/ceramic-infra ). I would just query the docId from the gateway directly. In theory the gateway should have access to the latest version.

**Comment by stbrody** [comment] 2020-12-04 14:09
The problem is that we don't want the "latest" version of the doc - we want the doc at exactly the version we are about to anchor.  Otherwise the metadata that we want to put into the bloom filter might be different in the version of the doc that the ceramic node we're talking to has compared to the version that we are about to anchor.

**Comment by stbrody** [comment] 2020-12-04 14:10
Also, if users are already configuring CAS instances with a Ceramic node to use, why wouldn't I just use that?  Why prefer our infra node and centralize things more than necessary?

**Comment by oed** [comment] 2020-12-04 15:01
> The problem is that we don't want the "latest" version of the doc

Why wouldn't we want that? That's what the `nonce` is for?

> Also, if users are already configuring CAS instances with a Ceramic node to use, why wouldn't I just use that? Why prefer our infra node and centralize things more than necessary?

Oh I more meant that we should use the gateway for our CAS.

**Comment by stbrody** [comment] 2020-12-04 18:42
depends on https://github.com/ceramicnetwork/js-ceramic/issues/592

**Closed** 2021-03-22 19:12 UTC
Labels: feature, p1
